import type { BlogPost } from "../types";
import reactImage from "../assets/images/react.jpg";
import typeScriptImage from "../assets/images/typescript.jpg";
import tailwindImage from "../assets/images/tailwind.jpg";

export const posts: BlogPost[] = [
  {
    id: 1,
    title: "Getting Started with React",
    description:
      "Learn the fundamentals of React and build your first component.",
    category: "React",
    readTime: "5 min read",
    image: reactImage,
    slug: "getting-started-with-react",
    author: "Adepoju Adeyinka",
    date: "July 8, 2026",
    content:
      "React is a JavaScript library for building user interfaces. It allows developers to create reusable components and build fast, interactive applications.",
  },
  {
    id: 2,
    title: "Understanding TypeScript",
    description:
      "Discover how TypeScript helps you write safer and more maintainable code.",
    category: "TypeScript",
    readTime: "7 min read",
    image: typeScriptImage,
    slug: "understanding-typescript",
    author: "Adepoju Adeyinka",
    date: "July 7, 2026",
    content:
      "TypeScript is a typed superset of JavaScript that compiles to plain JavaScript. It adds optional static typing, classes, interfaces, and more to help you build robust applications.",
  },
  {
    id: 3,
    title: "Styling with Tailwind CSS",
    description:
      "Build beautiful and responsive user interfaces using Tailwind CSS.",
    category: "Tailwind CSS",
    readTime: "6 min read",
    image: tailwindImage,
    slug: "styling-with-tailwind-css",
    author: "Adepoju Adeyinka",
    date: "July 6, 2026",
    content:
      "Tailwind CSS is a utility-first CSS framework that lets you build custom designs without leaving your HTML. It provides low-level utility classes that you can compose to build any design.",
  },
  {
    id: 7,
    title: "HTML5 Semantic Elements & Best Practices",
    description: "Learn how to structure your web pages using HTML5 semantic elements like header, nav, main, section, article, and footer.",
    category: "HTML",
    readTime: "5 min read",
    image: tailwindImage,
    slug: "html5-semantic-elements",
    author: "Adepoju Adeyinka",
    date: "July 11, 2026",
    content: "HTML5 introduced semantic elements that give meaning to your web page structure. Elements like <header>, <nav>, <main>, <section>, <article>, <aside>, and <footer> help with accessibility, SEO, and code readability. Using semantic HTML is the foundation of building well-structured, accessible websites.",
  },
  {
    id: 8,
    title: "CSS Grid vs Flexbox - When to Use Each",
    description: "Understand the differences between CSS Grid and Flexbox and when to use each layout method.",
    category: "CSS",
    readTime: "6 min read",
    image: tailwindImage,
    slug: "css-grid-vs-flexbox",
    author: "Adepoju Adeyinka",
    date: "July 10, 2026",
    content: "CSS Grid and Flexbox are both powerful layout tools, but they serve different purposes. Flexbox is best for one-dimensional layouts (rows or columns), while Grid excels at two-dimensional layouts with rows and columns simultaneously. Learn when to reach for each one to build responsive, maintainable layouts.",
  },
  {
    id: 9,
    title: "Getting Started with Bootstrap 5",
    description: "Build responsive, mobile-first websites quickly using Bootstrap 5's grid system and components.",
    category: "Bootstrap",
    readTime: "7 min read",
    image: reactImage,
    slug: "getting-started-with-bootstrap-5",
    author: "Adepoju Adeyinka",
    date: "July 9, 2026",
    content: "Bootstrap 5 is the latest version of the world's most popular CSS framework. It features a responsive grid system, pre-built components like navbars, cards, modals, and forms, and utility classes for rapid styling. Bootstrap 5 uses CSS custom properties and has dropped jQuery dependency for a modern approach.",
  },
  {
    id: 10,
    title: "Next.js - Full-Stack React Framework",
    description: "Explore Next.js features including SSR, SSG, API routes, and the App Router.",
    category: "Next.js",
    readTime: "8 min read",
    image: reactImage,
    slug: "nextjs-fullstack-framework",
    author: "Adepoju Adeyinka",
    date: "July 12, 2026",
    content: "Next.js is a React framework for building production-grade applications. It provides server-side rendering (SSR), static site generation (SSG), API routes for backend logic, file-based routing, image optimization, and middleware. The App Router with React Server Components represents the future of React development.",
  },
];

export const latestPosts: BlogPost[] = [
  {
    id: 4,
    title: "Understanding Flexbox Layouts",
    description: "Master CSS Flexbox by building responsive layouts step by step.",
    category: "CSS",
    readTime: "4 min read",
    image: tailwindImage,
    slug: "understanding-flexbox",
    author: "Adepoju Adeyinka",
    date: "July 5, 2026",
    content: "Flexbox is a one-dimensional layout method for arranging items in rows or columns. Items flex to fill additional space and shrink to fit into smaller spaces. With properties like justify-content, align-items, and flex-wrap, you can create complex responsive layouts with minimal code.",
  },
  {
    id: 5,
    title: "JavaScript Array Methods",
    description: "Learn map(), filter(), and reduce() with practical examples.",
    category: "JavaScript",
    readTime: "6 min read",
    image: typeScriptImage,
    slug: "javascript-array-methods",
    author: "Adepoju Adeyinka",
    date: "July 4, 2026",
    content: "JavaScript arrays come with powerful built-in methods. map() transforms each element, filter() selects elements based on a condition, and reduce() accumulates values.",
  },
  {
    id: 6,
    title: "React Hooks Explained",
    description: "Understand useState and useEffect with simple examples.",
    category: "React",
    readTime: "8 min read",
    image: reactImage,
    slug: "react-hooks-explained",
    author: "Adepoju Adeyinka",
    date: "July 3, 2026",
    content: "React Hooks let you use state and other React features without writing a class. useState manages component state, while useEffect handles side effects like data fetching.",
  },
  {
    id: 11,
    title: "HTML Forms - From Basics to Advanced",
    description: "Learn how to create accessible, well-structured HTML forms with validation.",
    category: "HTML",
    readTime: "5 min read",
    image: typeScriptImage,
    slug: "html-forms-complete-guide",
    author: "Adepoju Adeyinka",
    date: "July 2, 2026",
    content: "HTML forms are the primary way users interact with web applications. Learn about input types (text, email, password, date, range), form validation using built-in HTML5 attributes like required, pattern, min/max, and how to structure forms with fieldset, legend, and labels for accessibility.",
  },
  {
    id: 12,
    title: "CSS Custom Properties for Theming",
    description: "Use CSS custom properties (variables) to create dynamic, maintainable themes.",
    category: "CSS",
    readTime: "4 min read",
    image: tailwindImage,
    slug: "css-custom-properties-theming",
    author: "Adepoju Adeyinka",
    date: "July 1, 2026",
    content: "CSS custom properties (variables) allow you to define reusable values and create dynamic themes. Declared with --name and accessed with var(), they support inheritance, can be changed at runtime with JavaScript, and enable dark mode toggling with just a few lines of code.",
  },
  {
    id: 13,
    title: "Responsive Design with Bootstrap Grid",
    description: "Build mobile-first layouts using Bootstrap's powerful grid system.",
    category: "Bootstrap",
    readTime: "6 min read",
    image: reactImage,
    slug: "bootstrap-grid-responsive",
    author: "Adepoju Adeyinka",
    date: "June 30, 2026",
    content: "Bootstrap's grid system uses containers, rows, and columns to create responsive layouts. With breakpoints (xs, sm, md, lg, xl, xxl) you control how content stacks or displays side-by-side across different screen sizes. Combined with utility classes, you can build complex layouts without writing custom CSS.",
  },
  {
    id: 14,
    title: "Node.js & Express - Your First REST API",
    description: "Build a simple REST API using Node.js and Express framework.",
    category: "Node.js",
    readTime: "7 min read",
    image: typeScriptImage,
    slug: "nodejs-express-rest-api",
    author: "Adepoju Adeyinka",
    date: "June 28, 2026",
    content: "Node.js allows JavaScript to run on the server, and Express provides a minimal framework for building web applications and APIs. Learn how to set up routes, handle requests, serve JSON, and connect to a database to create a fully functional REST API.",
  },
  {
    id: 15,
    title: "Python for Web Development",
    description: "Discover why Python is a top choice for backend web development.",
    category: "Python",
    readTime: "5 min read",
    image: typeScriptImage,
    slug: "python-web-development",
    author: "Adepoju Adeyinka",
    date: "June 26, 2026",
    content: "Python is a versatile language widely used in web development. With frameworks like Django for large applications and Flask/FastAPI for lightweight APIs, Python offers excellent developer experience, extensive libraries, and strong community support for building web applications.",
  },
  {
    id: 16,
    title: "Introduction to Docker for Developers",
    description: "Containerize your applications with Docker for consistent development and deployment.",
    category: "DevOps",
    readTime: "8 min read",
    image: reactImage,
    slug: "docker-for-developers",
    author: "Adepoju Adeyinka",
    date: "June 24, 2026",
    content: "Docker packages your application and its dependencies into containers that run consistently across environments. Learn about Dockerfiles, images, containers, and Docker Compose for multi-service applications. Docker eliminates 'it works on my machine' problems.",
  },
];